// Verified Spotify track IDs for every catalog song available on the
// platform. Generated from official album and playlist listings, each ID
// validated live before inclusion. Songs absent here (all of Endless,
// most of Nostalgia Ultra, Golden Girl) have never been released to
// Spotify, so no embed can exist for them.

export const TRACK_IDS: Record<string, string> = {
  "Bad Religion": "6jy12gDerHRUSwiEhfs9C6",
  "Be Yourself": "1IdZvb2XK8NmsovQlV6CPn",
  "Biking": "2q0VexHJirnUPnEOhr2DxK",
  "Cayendo": "72794Eag03xdy7TO0KNuid",
  "Chanel": "6Nle9hKrkL1wQpwNfEkxjh",
  "Close to You": "1VZLEW5ZfcAbKZ94XQiSZF",
  "Crack Rock": "125FPswReMD9Ggvn69M7Ch",
  "DHL": "2INhKpUdzh7v0j041gZNsz",
  "Dear April": "62ljuuXo0zrcrtJnnOhfxT",
  "Facebook Story": "73D5hBkiVZkopZrmBZTBWf",
  "Fertilizer": "5MXB4YBEm0GZwS9Nbs3JqM",
  "Forrest Gump": "6RBAJlxHY9Ulvw2y7yk4aX",
  "Futura Free": "5k8LB57xOq8UUNVaKWSqrf",
  "Godspeed": "34xTFwjPQ1dC6uJmleno7x",
  "Good Guy": "2JUqYobT8NvARdPmc4ES2x",
  "In My Room": "4S4Mfvv03M1cHgIOJcbUCL",
  "Ivy": "2ZWlPOoWh0626oTaHrnl2a",
  "Lens": "371H6HjS4SXGbQ9IVfFUIL",
  "Lost": "4L7jMAP8UcIe309yQmkdcO",
  "Made in America (with Jay-Z and Kanye West)": "57CdogxwhzdHhqjj0115He",
  "Monks": "3YXVl3FvIrvhgSW9ME3qNf",
  "Moon River": "41cpvQ2GyGb2BRdIRSsTqK",
  "Nights": "7eqoqGkKwgOaWNNHx90uEZ",
  "Nikes": "19YKaevk2bce4odJkP5L22",
  "No Church in the Wild (with Jay-Z and Kanye West)": "0aFObVR01JzPbBMjze4xPV",
  "Novacane": "4osgfFTICMkcGbbigdsa53",
  "Oceans (Jay-Z featuring Frank Ocean)": "4gKy4mu2gkMEUyXD5peMIr",
  "Oldie (Odd Future)": "53dkS3h9uTNsWYZTPacnpx",
  "Pilot Jones": "5ITIiswssMSAdTJ9ZDEI8D",
  "Pink + White": "3xKsf9qdS1CyvXSMEid6g8",
  "Pink Matter": "0C3W4yLCuyUxIEwkSpBO8H",
  "Pretty Sweet": "17yrCsl1Ai6CZLBmGj6d6p",
  "Provider": "6R6ihJhRbgu7JxJKIbW57w",
  "Purity (A$AP Rocky featuring Frank Ocean)": "2MF4HtZHBoUliOi9nOAbS0",
  "Pyramids": "0rbK15g3UsDTVy1EuwgKYz",
  "RAF (A$AP Mob featuring Frank Ocean)": "6kl1qtQXQsFiIWRBK24Cfp",
  "Rushes": "2l3f3PNLSOISQpUzm1m4j0",
  "Seigfried": "1BViPjTT585XAhkUUrkts0",
  "Self Control": "5GUYJTQap5F3RDQiCOJhrS",
  "She (Tyler, the Creator featuring Frank Ocean)": "5WzfCu5fhgm7jv896EN1Md",
  "Sierra Leone": "4XgpXhvf9JBbKPtX84DFN7",
  "Skyline To": "4xR3MAscflQ262kMeiKshQ",
  "Slide (Calvin Harris featuring Frank Ocean and Migos)": "09asRqtDMkv88nL1tVfgks",
  "Solo": "35xSkNIXi504fcEwz9USRB",
  "Solo (Reprise)": "2qtoRFCOEL1gRn5q9DJC7F",
  "Strawberry Swing": "1RLbxJMHhyv6s7sIo4JbIC",
  "Sunday (Earl Sweatshirt featuring Frank Ocean)": "0fAehaneUJdlSlWXYe1KZp",
  "Super Rich Kids": "0K9oqDmJBgSFjXU1bUY9Fk",
  "Superpower (Beyonce featuring Frank Ocean)": "49sXkAcR5LvOrtq5Qcn5cf",
  "Sweet Life": "6fbjdXZNtoAJbJZUeT87Ii",
  "Swim Good": "0ytw2owVvegkIS87txqV1O",
  "Thinkin Bout You": "5mphdlILgAq3vh1MSvAJTS",
  "White": "6j9pCKVaJYNF7AdaNVTAaE",
  "White Ferrari": "2LMkwUfqC6S6s6qDVlEuzV",
};
