export interface Artist {
  id: string;
  artistName: string;
  coverImageUrl: string;
  category: string;
  year: number;
  status: "active" | "coming-soon";
  // h,s,l values (e.g. "260, 70%, 55%") -- the page's ambient tint shifts
  // to this color when the artist's card is hovered
  accentHsl?: string;
  teaser?: string;
}

export type ChapterMood =
  | "nostalgic"
  | "melancholic"
  | "triumphant"
  | "introspective"
  | "romantic"
  | "rebellious"
  | "peaceful"
  | "intense"
  | "playful"
  | "wonder";

export interface ChapterAmbience {
  mood: ChapterMood;
  // h,s,l values only (e.g. "260, 70%, 55%"), consumed as --chapter-hsl
  accentHsl: string;
  // Manually curated per chapter; never pipeline output
  spotifyTrackId?: string | null;
  imageryHint?: string;
}

export interface StoryChapter {
  id: string;
  order: number; // 1-indexed; explicit so chapters can be reordered safely
  title: string;
  content: string;
  ambience: ChapterAmbience;
}

export interface ArtistStory {
  schemaVersion: 2;
  title: string;
  artistSlug: string;
  chapters: StoryChapter[];
}

// v1 story shape, kept only for the backward-compat normalizer
export interface LegacyArtistStory {
  title: string;
  sections: Array<{ id: string; title: string; content: string }>;
}

// Song bubble universe, generated by the backend pipeline.
// Keys are snake_case to match the Python-written JSON contract.
export interface SongBubble {
  song_name: string;
  story: string;
  mood: string;
  bubble_color: string;
}

// Public projection written by the pipeline into data/public/stories/.
// Bubbles only; internal generation metadata never enters this artifact.
export interface SongUniverse {
  artist_slug: string;
  song_bubbles: SongBubble[];
}

// Cultural legacy dataset, generated by the backend pipeline.
// Keys are snake_case to match the Python-written JSON contract.
export interface LegacyVoice {
  quote: string;
  speaker: string;
}

export interface LegacyPillar {
  id: string;
  numeral: string;
  title: string;
  tagline: string;
  mood: string;
  accent_hsl: string;
  story: string;
  moments: string[];
  voices: LegacyVoice[];
}

export interface ArtistLegacy {
  artist_slug: string;
  pillars: LegacyPillar[];
}

export interface ResearchFile {
  metadata: {
    timestamp: string;
    query_type: string;
    artist_name: string;
    model_used: string;
    tokens_used: number;
    cost_estimate: number;
  };
  response: Record<string, unknown>;
}
